name: Update nginx
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Build and start nginx container
        run: |
          docker build -t nginx_own -f nginx.Dockerfile .
          docker ps -aq --filter "name=nginx" | grep -q . && docker stop nginx && docker rm -f nginx
          docker run -d \
            --name=nginx \
            --restart=always \
            -p 80:80 \
            nginx_own:latest
          docker network connect sports-location-tracker_stg nginx
          docker network connect datavarasto-stg_stg nginx
