name: Update nginx
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Build and start nginx container
        run: |
          docker build -t nginx_own -f nginx.Dockerfile .
          docker run -d \
            --restart=always \
            --network=sports-location-tracker_stg \
            -p 80:80 \
            nginx_own:latest
